version: "3"

services:
  web:
    image: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./html:/usr/share/nginx/html
    ports:
    - "8080:80"
    # environment:
    # - NGINX_HOST=foobar.com
    # - NGINX_PORT=80