---
- name: Install nginx
  hosts: all
  become: true

  tasks:
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Install rsync
    yum:
      name: rsync
      state: present

  - name: Creates dev directory
    file:
      path: /usr/share/nginx/html/dev/
      state: directory
  - name: Creates staging directory
    file:
      path: /usr/share/nginx/html/staging/
      state: directory

  - name: Insert dev Page
    template:
      src: index-dev.html
      dest: /usr/share/nginx/html/dev/index.html
  - name: Insert staging Page
    template:
      src: index-staging.html
      dest: /usr/share/nginx/html/staging/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started
