name: Update Hugo (dev)


on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: git checkout branches - src and gh-pages 
        run: |
          git worktree add -B gh-pages public origin/gh-pages
          git worktree add -B src src origin/src
          git branch 

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'

      - name: Install fortune
        run: |
          sudo apt-get install fortune

      - name: Build
        run: |
          cd src
          go install

      - name: Update Hugo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email 'jizu.sun@users.noreply.github.com'
          echo "/usr/games" >> $GITHUB_PATH
          wiredcraft-hugo dev
      
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: hugo-deploy.yml
          directory: ./ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory hosts
            --limit dev
            --extra-vars hello=there
            --verbose

      - name: Show the current website version
        run: |
          cat config/_default/params.toml

      - name: Verify the deployed version 
        run: |
          curl -s http://dev.wiredcraft.edtechstar.com/ | grep Version
