name: Update Hugo

on:
  push:
    branches: 
      - hugo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: git checkout branches - src and gh-pages 
        run: |
          git worktree add -B gh-pages public origin/gh-pages
          git worktree add -B src src origin/src
          git branch 

