name: Update Hugo

on:
  push:
    branches: 
      - hugo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: git checkout branches - src and gh-pages 
        run: |
          git worktree add -B gh-pages public origin/gh-pages
          git worktree add -B src src origin/src
          git branch 

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'

      - name: Install fortune
        run: |
          sudo apt-get install fortune
          /usr/games/fortune
          fortune

      - name: Build
        run: |
          cd src
          go install

      - name: Update Hugo
        run: |
          which wiredcraft-hugo
          wiredcraft-hugo dev

