name: Update Hugo

on:
  push:
    branches: 
      - hugo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: git checkout branches - src and gh-pages 
        run: |
          git worktree add -B gh-pages public origin/gh-pages
          git worktree add -B src src origin/src
          git branch 
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Build
        run: |
          cd src
          make build
          mv build/main /usr/local/bin/hugoctl
          echo $PATH
      - name: Update Hugo
        run: |
          hugoctl dev

