name: Update Hugo (staging)


on:
  schedule:
    - cron: "*/* * * * *"
  push:
    branches: 
      - hugo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: git checkout branches - src and gh-pages 
        run: |
          git worktree add -B gh-pages public origin/gh-pages
          git worktree add -B src src origin/src
          git branch 

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'

      - name: Install fortune
        run: |
          sudo apt-get install fortune

      - name: Build
        run: |
          cd src
          go install

      - name: Update Hugo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email 'jizu.sun@users.noreply.github.com'
          echo "/usr/games" >> $GITHUB_PATH
          wiredcraft-hugo staging

  deploy:
    name: Deploy
    runs-on: ubuntu-latest 
    needs: [build]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Show the website version
        run: |
          cat config/_default/params.toml
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
      - name: Build
        run: hugo

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: hugo-deploy.yml
          directory: ./ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory hosts
            --limit staging
            --extra-vars hello=there
            --verbose
      - name: Check the deployed version 
        run: |
          curl -s http://staging.wiredcraft.edtechstar.com/ | grep Version
